// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteFileData, DeleteFileErrors, DeleteFileResponses, GeneratePresignedUploadUrlData, GeneratePresignedUploadUrlErrors, GeneratePresignedUploadUrlResponses, GetApiMapsAutocompleteData, GetApiMapsAutocompleteErrors, GetApiMapsAutocompleteResponses, GetApiMapsPlaceDetailsData, GetApiMapsPlaceDetailsErrors, GetApiMapsPlaceDetailsResponses, GetApiMapsPlaceTypesData, GetApiMapsPlaceTypesResponses, GetApiMapsSearchNearbyWithDetailsData, GetApiMapsSearchNearbyWithDetailsErrors, GetApiMapsSearchNearbyWithDetailsResponses, GetApiMapsV2AutocompleteData, GetApiMapsV2AutocompleteErrors, GetApiMapsV2AutocompleteResponses, GetApiMapsV2PlaceDetailsData, GetApiMapsV2PlaceDetailsErrors, GetApiMapsV2PlaceDetailsResponses, GetApiMapsV2PlaceTypesData, GetApiMapsV2PlaceTypesResponses, GetApiMapsV2SearchNearbyWithDetailsData, GetApiMapsV2SearchNearbyWithDetailsErrors, GetApiMapsV2SearchNearbyWithDetailsResponses, GetApiPlacesByIdData, GetApiPlacesByIdErrors, GetApiPlacesByIdResponses, GetApiPlacesData, GetApiPlacesErrors, GetApiPlacesResponses, GetApiReviewsPlaceByPlaceIdData, GetApiReviewsPlaceByPlaceIdErrors, GetApiReviewsPlaceByPlaceIdResponses, GetFileInfoData, GetFileInfoErrors, GetFileInfoResponses, ListFilesData, ListFilesErrors, ListFilesResponses, PatchApiPlacesByPlaceIdData, PatchApiPlacesByPlaceIdErrors, PatchApiPlacesByPlaceIdResponses, PostApiAuthLoginData, PostApiAuthLoginErrors, PostApiAuthLoginResponses, PostApiAuthRegisterData, PostApiAuthRegisterErrors, PostApiAuthRegisterResponses, PostApiPlacesImportFromMapData, PostApiPlacesImportFromMapErrors, PostApiPlacesImportFromMapResponses, PostApiReviewsData, PostApiReviewsErrors, PostApiReviewsResponses, UploadFileData, UploadFileErrors, UploadFileResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Login
 *
 * Authenticate user and return JWT token
 */
export const postApiAuthLogin = <ThrowOnError extends boolean = false>(options?: Options<PostApiAuthLoginData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostApiAuthLoginResponses, PostApiAuthLoginErrors, ThrowOnError>({
        url: '/api/auth/login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Register
 *
 * Create new user account
 */
export const postApiAuthRegister = <ThrowOnError extends boolean = false>(options?: Options<PostApiAuthRegisterData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostApiAuthRegisterResponses, PostApiAuthRegisterErrors, ThrowOnError>({
        url: '/api/auth/register',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get all places
 *
 * Get list of places with optional filters
 */
export const getApiPlaces = <ThrowOnError extends boolean = false>(options?: Options<GetApiPlacesData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiPlacesResponses, GetApiPlacesErrors, ThrowOnError>({
        url: '/api/places',
        ...options
    });
};

/**
 * Get place by ID
 */
export const getApiPlacesById = <ThrowOnError extends boolean = false>(options: Options<GetApiPlacesByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetApiPlacesByIdResponses, GetApiPlacesByIdErrors, ThrowOnError>({
        url: '/api/places/{id}',
        ...options
    });
};

/**
 * Import place from Goong Maps
 *
 * Fetch place details from Goong Maps and save to database
 */
export const postApiPlacesImportFromMap = <ThrowOnError extends boolean = false>(options?: Options<PostApiPlacesImportFromMapData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostApiPlacesImportFromMapResponses, PostApiPlacesImportFromMapErrors, ThrowOnError>({
        url: '/api/places/import-from-map',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Update place information
 *
 * Update additional information for a place (requires authentication)
 */
export const patchApiPlacesByPlaceId = <ThrowOnError extends boolean = false>(options: Options<PatchApiPlacesByPlaceIdData, ThrowOnError>) => {
    return (options.client ?? client).patch<PatchApiPlacesByPlaceIdResponses, PatchApiPlacesByPlaceIdErrors, ThrowOnError>({
        url: '/api/places/{placeId}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get available place types
 *
 * List of place types (static list for OSM)
 */
export const getApiMapsPlaceTypes = <ThrowOnError extends boolean = false>(options?: Options<GetApiMapsPlaceTypesData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiMapsPlaceTypesResponses, unknown, ThrowOnError>({
        url: '/api/maps/place-types',
        ...options
    });
};

/**
 * Autocomplete place search (OSM)
 */
export const getApiMapsAutocomplete = <ThrowOnError extends boolean = false>(options: Options<GetApiMapsAutocompleteData, ThrowOnError>) => {
    return (options.client ?? client).get<GetApiMapsAutocompleteResponses, GetApiMapsAutocompleteErrors, ThrowOnError>({
        url: '/api/maps/autocomplete',
        ...options
    });
};

/**
 * Get place details (OSM)
 */
export const getApiMapsPlaceDetails = <ThrowOnError extends boolean = false>(options: Options<GetApiMapsPlaceDetailsData, ThrowOnError>) => {
    return (options.client ?? client).get<GetApiMapsPlaceDetailsResponses, GetApiMapsPlaceDetailsErrors, ThrowOnError>({
        url: '/api/maps/place-details',
        ...options
    });
};

/**
 * Search nearby places (OSM)
 */
export const getApiMapsSearchNearbyWithDetails = <ThrowOnError extends boolean = false>(options: Options<GetApiMapsSearchNearbyWithDetailsData, ThrowOnError>) => {
    return (options.client ?? client).get<GetApiMapsSearchNearbyWithDetailsResponses, GetApiMapsSearchNearbyWithDetailsErrors, ThrowOnError>({
        url: '/api/maps/search-nearby-with-details',
        ...options
    });
};

/**
 * Get available place types
 *
 * List of place types for Goong API
 */
export const getApiMapsV2PlaceTypes = <ThrowOnError extends boolean = false>(options?: Options<GetApiMapsV2PlaceTypesData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiMapsV2PlaceTypesResponses, unknown, ThrowOnError>({
        url: '/api/maps-v2/place-types',
        ...options
    });
};

/**
 * Autocomplete place search (Goong)
 *
 *
 * Places Search by keyword with autocomplete.
 *
 * **Session Token Usage:**
 * - Use UUID v4 to group multiple autocomplete requests in one search session
 * - Helps optimize billing (charges per session instead of per request)
 * - Enables better caching and analytics
 * - Example: a68dfa01-a5aa-47d1-aaa7-a3184896b283
 *
 * **Location Format:** latitude,longitude (e.g., "21.0285,105.8542")
 *
 */
export const getApiMapsV2Autocomplete = <ThrowOnError extends boolean = false>(options: Options<GetApiMapsV2AutocompleteData, ThrowOnError>) => {
    return (options.client ?? client).get<GetApiMapsV2AutocompleteResponses, GetApiMapsV2AutocompleteErrors, ThrowOnError>({
        url: '/api/maps-v2/autocomplete',
        ...options
    });
};

/**
 * Get place details (Goong)
 */
export const getApiMapsV2PlaceDetails = <ThrowOnError extends boolean = false>(options: Options<GetApiMapsV2PlaceDetailsData, ThrowOnError>) => {
    return (options.client ?? client).get<GetApiMapsV2PlaceDetailsResponses, GetApiMapsV2PlaceDetailsErrors, ThrowOnError>({
        url: '/api/maps-v2/place-details',
        ...options
    });
};

/**
 * Search nearby places (Goong)
 */
export const getApiMapsV2SearchNearbyWithDetails = <ThrowOnError extends boolean = false>(options: Options<GetApiMapsV2SearchNearbyWithDetailsData, ThrowOnError>) => {
    return (options.client ?? client).get<GetApiMapsV2SearchNearbyWithDetailsResponses, GetApiMapsV2SearchNearbyWithDetailsErrors, ThrowOnError>({
        url: '/api/maps-v2/search-nearby-with-details',
        ...options
    });
};

/**
 * Create a review
 *
 * Create a new review for a place
 */
export const postApiReviews = <ThrowOnError extends boolean = false>(options?: Options<PostApiReviewsData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostApiReviewsResponses, PostApiReviewsErrors, ThrowOnError>({
        url: '/api/reviews',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get place reviews
 *
 * Get all reviews for a specific place
 */
export const getApiReviewsPlaceByPlaceId = <ThrowOnError extends boolean = false>(options: Options<GetApiReviewsPlaceByPlaceIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetApiReviewsPlaceByPlaceIdResponses, GetApiReviewsPlaceByPlaceIdErrors, ThrowOnError>({
        url: '/api/reviews/place/{placeId}',
        ...options
    });
};

/**
 * Upload file to MinIO storage
 */
export const uploadFile = <ThrowOnError extends boolean = false>(options?: Options<UploadFileData, ThrowOnError>) => {
    return (options?.client ?? client).post<UploadFileResponses, UploadFileErrors, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/api/minio/upload',
        ...options,
        headers: {
            'Content-Type': null,
            ...options?.headers
        }
    });
};

/**
 * Generate a presigned URL for uploading files
 */
export const generatePresignedUploadUrl = <ThrowOnError extends boolean = false>(options: Options<GeneratePresignedUploadUrlData, ThrowOnError>) => {
    return (options.client ?? client).get<GeneratePresignedUploadUrlResponses, GeneratePresignedUploadUrlErrors, ThrowOnError>({
        url: '/api/minio/presigned-upload-url',
        ...options
    });
};

/**
 * Get file information from MinIO
 */
export const getFileInfo = <ThrowOnError extends boolean = false>(options: Options<GetFileInfoData, ThrowOnError>) => {
    return (options.client ?? client).get<GetFileInfoResponses, GetFileInfoErrors, ThrowOnError>({
        url: '/api/minio/file-info',
        ...options
    });
};

/**
 * Delete file from MinIO storage
 */
export const deleteFile = <ThrowOnError extends boolean = false>(options: Options<DeleteFileData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteFileResponses, DeleteFileErrors, ThrowOnError>({
        url: '/api/minio/delete',
        ...options
    });
};

/**
 * List files in MinIO bucket
 */
export const listFiles = <ThrowOnError extends boolean = false>(options?: Options<ListFilesData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListFilesResponses, ListFilesErrors, ThrowOnError>({
        url: '/api/minio/files',
        ...options
    });
};
