// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetApiMapsAutocompleteData, GetApiMapsAutocompleteErrors, GetApiMapsAutocompleteResponses, GetApiMapsNearbyData, GetApiMapsNearbyErrors, GetApiMapsNearbyResponses, GetApiMapsPlaceDetailsData, GetApiMapsPlaceDetailsErrors, GetApiMapsPlaceDetailsResponses, GetApiMapsPlaceTypesData, GetApiMapsPlaceTypesResponses, GetApiMapsSearchNearbyWithDetailsData, GetApiMapsSearchNearbyWithDetailsErrors, GetApiMapsSearchNearbyWithDetailsResponses, GetApiPlacesByIdData, GetApiPlacesByIdErrors, GetApiPlacesByIdResponses, GetApiPlacesData, GetApiPlacesErrors, GetApiPlacesResponses, PostApiAuthLoginData, PostApiAuthLoginErrors, PostApiAuthLoginResponses, PostApiAuthRegisterData, PostApiAuthRegisterErrors, PostApiAuthRegisterResponses, PostApiPlacesImportFromMapData, PostApiPlacesImportFromMapErrors, PostApiPlacesImportFromMapResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Login
 *
 * Authenticate user and return JWT token
 */
export const postApiAuthLogin = <ThrowOnError extends boolean = false>(options?: Options<PostApiAuthLoginData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostApiAuthLoginResponses, PostApiAuthLoginErrors, ThrowOnError>({
        url: '/api/auth/login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Register
 *
 * Create new user account
 */
export const postApiAuthRegister = <ThrowOnError extends boolean = false>(options?: Options<PostApiAuthRegisterData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostApiAuthRegisterResponses, PostApiAuthRegisterErrors, ThrowOnError>({
        url: '/api/auth/register',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get all places
 *
 * Get list of places with optional filters
 */
export const getApiPlaces = <ThrowOnError extends boolean = false>(options?: Options<GetApiPlacesData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiPlacesResponses, GetApiPlacesErrors, ThrowOnError>({
        url: '/api/places',
        ...options
    });
};

/**
 * Get place by ID
 */
export const getApiPlacesById = <ThrowOnError extends boolean = false>(options: Options<GetApiPlacesByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetApiPlacesByIdResponses, GetApiPlacesByIdErrors, ThrowOnError>({
        url: '/api/places/{id}',
        ...options
    });
};

/**
 * Import place from Track-Asia Maps
 *
 * Fetch place details from Track-Asia Maps and save to database
 */
export const postApiPlacesImportFromMap = <ThrowOnError extends boolean = false>(options?: Options<PostApiPlacesImportFromMapData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostApiPlacesImportFromMapResponses, PostApiPlacesImportFromMapErrors, ThrowOnError>({
        url: '/api/places/import-from-map',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Search nearby places
 *
 * Search for nearby places using Track-Asia Maps API based on location and optional filters
 */
export const getApiMapsNearby = <ThrowOnError extends boolean = false>(options: Options<GetApiMapsNearbyData, ThrowOnError>) => {
    return (options.client ?? client).get<GetApiMapsNearbyResponses, GetApiMapsNearbyErrors, ThrowOnError>({
        url: '/api/maps/nearby',
        ...options
    });
};

/**
 * Get place details
 *
 * Get detailed information about a specific place using Track-Asia Maps API
 */
export const getApiMapsPlaceDetails = <ThrowOnError extends boolean = false>(options: Options<GetApiMapsPlaceDetailsData, ThrowOnError>) => {
    return (options.client ?? client).get<GetApiMapsPlaceDetailsResponses, GetApiMapsPlaceDetailsErrors, ThrowOnError>({
        url: '/api/maps/place-details',
        ...options
    });
};

/**
 * Get available place types
 *
 * Get list of place types that can be used for nearby search
 */
export const getApiMapsPlaceTypes = <ThrowOnError extends boolean = false>(options?: Options<GetApiMapsPlaceTypesData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiMapsPlaceTypesResponses, unknown, ThrowOnError>({
        url: '/api/maps/place-types',
        ...options
    });
};

/**
 * Autocomplete place search
 *
 * Get autocomplete suggestions for place search
 */
export const getApiMapsAutocomplete = <ThrowOnError extends boolean = false>(options: Options<GetApiMapsAutocompleteData, ThrowOnError>) => {
    return (options.client ?? client).get<GetApiMapsAutocompleteResponses, GetApiMapsAutocompleteErrors, ThrowOnError>({
        url: '/api/maps/autocomplete',
        ...options
    });
};

/**
 * Search nearby places with full details
 *
 * Combines autocomplete and place-details APIs, filters by distance and type
 */
export const getApiMapsSearchNearbyWithDetails = <ThrowOnError extends boolean = false>(options: Options<GetApiMapsSearchNearbyWithDetailsData, ThrowOnError>) => {
    return (options.client ?? client).get<GetApiMapsSearchNearbyWithDetailsResponses, GetApiMapsSearchNearbyWithDetailsErrors, ThrowOnError>({
        url: '/api/maps/search-nearby-with-details',
        ...options
    });
};
