// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};

export type PostApiAuthLoginData = {
    body?: {
        /**
         * Email address
         */
        email: string;
        /**
         * Password
         */
        password: string;
    };
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type PostApiAuthLoginErrors = {
    /**
     * Invalid credentials
     */
    401: {
        /**
         * Error message
         */
        error: string;
    };
    /**
     * Internal server error
     */
    500: {
        /**
         * Error message
         */
        error: string;
    };
};

export type PostApiAuthLoginError = PostApiAuthLoginErrors[keyof PostApiAuthLoginErrors];

export type PostApiAuthLoginResponses = {
    /**
     * Login successful
     */
    200: {
        /**
         * JWT authentication token
         */
        token: string;
        user: {
            id: string;
            email: string;
            name: string;
            role: 'USER' | 'ADMIN';
        };
    };
};

export type PostApiAuthLoginResponse = PostApiAuthLoginResponses[keyof PostApiAuthLoginResponses];

export type PostApiAuthRegisterData = {
    body?: {
        /**
         * Email address
         */
        email: string;
        /**
         * Password (minimum 6 characters)
         */
        password: string;
        /**
         * Full name
         */
        name: string;
        /**
         * Phone number
         */
        phoneNumber?: string;
        /**
         * Address
         */
        address?: string;
        /**
         * Number of kids
         */
        numberOfKids?: number;
    };
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type PostApiAuthRegisterErrors = {
    /**
     * Invalid input or email already exists
     */
    400: {
        /**
         * Error message
         */
        error: string;
    };
    /**
     * Internal server error
     */
    500: {
        /**
         * Error message
         */
        error: string;
    };
};

export type PostApiAuthRegisterError = PostApiAuthRegisterErrors[keyof PostApiAuthRegisterErrors];

export type PostApiAuthRegisterResponses = {
    /**
     * Registration successful
     */
    201: {
        /**
         * JWT authentication token
         */
        token: string;
        user: {
            id: string;
            email: string;
            name: string;
            role: 'USER' | 'ADMIN';
        };
    };
};

export type PostApiAuthRegisterResponse = PostApiAuthRegisterResponses[keyof PostApiAuthRegisterResponses];

export type GetApiPlacesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Search by name or address
         */
        search?: string;
        /**
         * Filter by place type
         */
        placeType?: 'INDOOR' | 'OUTDOOR';
        /**
         * Minimum age
         */
        minAge?: string;
        /**
         * Maximum age
         */
        maxAge?: string;
        /**
         * Number of results
         */
        limit?: string;
        /**
         * Offset for pagination
         */
        offset?: string;
    };
    url: '/api/places';
};

export type GetApiPlacesErrors = {
    /**
     * Internal server error
     */
    500: {
        error: string;
    };
};

export type GetApiPlacesError = GetApiPlacesErrors[keyof GetApiPlacesErrors];

export type GetApiPlacesResponses = {
    /**
     * List of places
     */
    200: {
        places: Array<{
            id: string;
            name: string;
            description: string | null;
            address: string;
            latitude: number;
            longitude: number;
            placeType: 'INDOOR' | 'OUTDOOR';
            minAge: number;
            maxAge: number;
            area: number | null;
            openingTime: string | null;
            closingTime: string | null;
            phoneNumber: string | null;
            website: string | null;
            imageUrl: string | null;
            averageRating: number;
            totalReviews: number;
            createdAt: string;
            updatedAt: string;
        }>;
        total: number;
    };
};

export type GetApiPlacesResponse = GetApiPlacesResponses[keyof GetApiPlacesResponses];

export type GetApiPlacesByIdData = {
    body?: never;
    path: {
        /**
         * Place ID
         */
        id: string;
    };
    query?: never;
    url: '/api/places/{id}';
};

export type GetApiPlacesByIdErrors = {
    /**
     * Place not found
     */
    404: {
        error: string;
    };
    /**
     * Internal server error
     */
    500: {
        error: string;
    };
};

export type GetApiPlacesByIdError = GetApiPlacesByIdErrors[keyof GetApiPlacesByIdErrors];

export type GetApiPlacesByIdResponses = {
    /**
     * Place details
     */
    200: {
        id: string;
        name: string;
        description: string | null;
        address: string;
        latitude: number;
        longitude: number;
        placeType: 'INDOOR' | 'OUTDOOR';
        minAge: number;
        maxAge: number;
        area: number | null;
        openingTime: string | null;
        closingTime: string | null;
        phoneNumber: string | null;
        website: string | null;
        imageUrl: string | null;
        averageRating: number;
        totalReviews: number;
        createdAt: string;
        updatedAt: string;
    };
};

export type GetApiPlacesByIdResponse = GetApiPlacesByIdResponses[keyof GetApiPlacesByIdResponses];

export type PostApiPlacesImportFromMapData = {
    body?: {
        /**
         * Place ID from Goong Maps
         */
        place_id: string;
        /**
         * Type of place
         */
        placeType: 'INDOOR' | 'OUTDOOR';
        /**
         * Minimum age
         */
        minAge: number;
        /**
         * Maximum age
         */
        maxAge: number;
    };
    path?: never;
    query?: never;
    url: '/api/places/import-from-map';
};

export type PostApiPlacesImportFromMapErrors = {
    /**
     * Invalid data or place already exists
     */
    400: {
        error: string;
    };
    /**
     * Place not found on Goong Maps
     */
    404: {
        error: string;
    };
    /**
     * Internal server error
     */
    500: {
        error: string;
    };
};

export type PostApiPlacesImportFromMapError = PostApiPlacesImportFromMapErrors[keyof PostApiPlacesImportFromMapErrors];

export type PostApiPlacesImportFromMapResponses = {
    /**
     * Place imported successfully
     */
    201: {
        id: string;
        name: string;
        description: string | null;
        address: string;
        latitude: number;
        longitude: number;
        placeType: 'INDOOR' | 'OUTDOOR';
        minAge: number;
        maxAge: number;
        area: number | null;
        openingTime: string | null;
        closingTime: string | null;
        phoneNumber: string | null;
        website: string | null;
        imageUrl: string | null;
        averageRating: number;
        totalReviews: number;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostApiPlacesImportFromMapResponse = PostApiPlacesImportFromMapResponses[keyof PostApiPlacesImportFromMapResponses];

export type GetApiMapsNearbyData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Latitude of the location
         */
        latitude: string;
        /**
         * Longitude of the location
         */
        longitude: string;
        /**
         * Search radius in meters (default: 1000)
         */
        radius?: string;
        /**
         * Place types to search for (e.g., "restaurant|cafe|park")
         */
        type?: string;
    };
    url: '/api/maps/nearby';
};

export type GetApiMapsNearbyErrors = {
    /**
     * Invalid parameters
     */
    400: {
        error: string;
    };
    /**
     * Endpoint deprecated
     */
    410: {
        error: string;
    };
    /**
     * Internal server error or external API error
     */
    500: {
        error: string;
    };
};

export type GetApiMapsNearbyError = GetApiMapsNearbyErrors[keyof GetApiMapsNearbyErrors];

export type GetApiMapsNearbyResponses = {
    /**
     * Nearby places found successfully
     */
    200: {
        status: string;
        results: Array<{
            place_id: string;
            name: string;
            formatted_address: string;
            geometry: {
                location: {
                    lat: number;
                    lng: number;
                };
                location_type?: string;
                viewport?: {
                    northeast: {
                        lat: number;
                        lng: number;
                    };
                    southwest: {
                        lat: number;
                        lng: number;
                    };
                };
            };
            types?: Array<string>;
            icon?: string;
            vicinity?: string;
            class?: string;
            subclass?: string;
        }>;
        total: number;
    };
};

export type GetApiMapsNearbyResponse = GetApiMapsNearbyResponses[keyof GetApiMapsNearbyResponses];

export type GetApiMapsPlaceDetailsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Place ID from Goong Maps
         */
        place_id: string;
    };
    url: '/api/maps/place-details';
};

export type GetApiMapsPlaceDetailsErrors = {
    /**
     * Invalid parameters
     */
    400: {
        error: string;
    };
    /**
     * Place not found
     */
    404: {
        error: string;
    };
    /**
     * Internal server error
     */
    500: {
        error: string;
    };
};

export type GetApiMapsPlaceDetailsError = GetApiMapsPlaceDetailsErrors[keyof GetApiMapsPlaceDetailsErrors];

export type GetApiMapsPlaceDetailsResponses = {
    /**
     * Place details retrieved successfully
     */
    200: {
        status: string;
        result: {
            place_id: string;
            official_id?: string;
            name: string;
            formatted_address: string;
            vicinity?: string;
            adr_address?: string;
            editorial_summary?: {
                overview?: string;
            };
            address_components: Array<{
                long_name: string;
                short_name: string;
                types: Array<string>;
                official_id?: string;
            }>;
            geometry: {
                location: {
                    lat: number;
                    lng: number;
                };
                location_type?: string;
                viewport?: {
                    northeast: {
                        lat: number;
                        lng: number;
                    };
                    southwest: {
                        lat: number;
                        lng: number;
                    };
                };
            };
            plus_code?: {
                compound_code?: string;
                global_code?: string;
            };
            types: Array<string>;
            icon?: string;
            icon_background_color?: string;
            photos?: Array<{
                url: string;
            }>;
            opening_hours?: {
                open_now?: boolean;
                weekday_text?: Array<string>;
            };
            rating?: number;
            user_ratings_total?: number;
            website?: string;
            phone_number?: string;
            socials?: Array<string>;
            url?: string;
            utc_offset?: number;
            old_address_components?: Array<{
                long_name: string;
                short_name: string;
                types: Array<string>;
                official_id?: string;
            }>;
            old_formatted_address?: string;
        };
        html_attributions?: Array<string>;
    };
};

export type GetApiMapsPlaceDetailsResponse = GetApiMapsPlaceDetailsResponses[keyof GetApiMapsPlaceDetailsResponses];

export type GetApiMapsPlaceTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/maps/place-types';
};

export type GetApiMapsPlaceTypesResponses = {
    /**
     * List of available place types
     */
    200: {
        categories: Array<{
            name: string;
            types: Array<string>;
            description: string;
        }>;
    };
};

export type GetApiMapsPlaceTypesResponse = GetApiMapsPlaceTypesResponses[keyof GetApiMapsPlaceTypesResponses];

export type GetApiMapsAutocompleteData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Search input text (Required)
         */
        input: string;
        /**
         * Coordinates for location biased search (latitude,longitude)
         */
        location?: string;
        /**
         * Limit number of results. Defaults to 10
         */
        limit?: string;
        /**
         * Limits search to a radius from specified location (in km)
         */
        radius?: string;
        /**
         * Token to group multiple autocomplete requests in 1 session
         */
        sessiontoken?: string;
        /**
         * If true, returns fields like district, commune, province
         */
        more_compound?: string;
    };
    url: '/api/maps/autocomplete';
};

export type GetApiMapsAutocompleteErrors = {
    /**
     * Invalid parameters
     */
    400: {
        error: string;
    };
    /**
     * Internal server error
     */
    500: {
        error: string;
    };
};

export type GetApiMapsAutocompleteError = GetApiMapsAutocompleteErrors[keyof GetApiMapsAutocompleteErrors];

export type GetApiMapsAutocompleteResponses = {
    /**
     * Autocomplete suggestions
     */
    200: {
        status: string;
        predictions: Array<{
            description: string;
            place_id: string;
            reference?: string;
            structured_formatting: {
                main_text: string;
                secondary_text?: string;
            };
            matched_substrings?: Array<unknown>;
            terms?: Array<unknown>;
            has_children?: boolean;
            display_type?: string;
            score?: number;
            plus_code?: {
                compound_code?: string;
                global_code?: string;
            };
        }>;
    };
};

export type GetApiMapsAutocompleteResponse = GetApiMapsAutocompleteResponses[keyof GetApiMapsAutocompleteResponses];

export type GetApiMapsSearchNearbyWithDetailsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Search input text (keyword-based search)
         */
        input: string;
        /**
         * User latitude
         */
        latitude: string;
        /**
         * User longitude
         */
        longitude: string;
        /**
         * Search radius in meters (500, 1000, 2000, 5000, 10000)
         */
        radius?: string;
        /**
         * Maximum number of results
         */
        limit?: string;
        /**
         * Transportation profile for distance calculation
         */
        profile?: 'car' | 'moto' | 'bike';
    };
    url: '/api/maps/search-nearby-with-details';
};

export type GetApiMapsSearchNearbyWithDetailsErrors = {
    /**
     * Invalid parameters
     */
    400: {
        error: string;
    };
    /**
     * Internal server error
     */
    500: {
        error: string;
    };
};

export type GetApiMapsSearchNearbyWithDetailsError = GetApiMapsSearchNearbyWithDetailsErrors[keyof GetApiMapsSearchNearbyWithDetailsErrors];

export type GetApiMapsSearchNearbyWithDetailsResponses = {
    /**
     * Places found with details and distance filtering
     */
    200: {
        status: string;
        results: Array<{
            place_id: string;
            name: string;
            formatted_address: string;
            geometry: {
                location: {
                    lat: number;
                    lng: number;
                };
                location_type?: string;
                viewport?: {
                    northeast: {
                        lat: number;
                        lng: number;
                    };
                    southwest: {
                        lat: number;
                        lng: number;
                    };
                };
            };
            types: Array<string>;
            rating?: number;
            user_ratings_total?: number;
            photos?: Array<{
                url: string;
            }>;
            phone_number?: string;
            website?: string;
            opening_hours?: {
                open_now?: boolean;
                weekday_text?: Array<string>;
            };
            /**
             * Distance from user location in meters
             */
            distance: number;
            /**
             * Travel time from user location in seconds
             */
            duration?: number;
        }>;
        total: number;
        /**
         * Total places checked
         */
        searched: number;
    };
};

export type GetApiMapsSearchNearbyWithDetailsResponse = GetApiMapsSearchNearbyWithDetailsResponses[keyof GetApiMapsSearchNearbyWithDetailsResponses];

export type PostApiReviewsData = {
    body?: {
        /**
         * Place ID from database
         */
        placeId: string;
        /**
         * Rating from 1 to 5
         */
        rating: number;
        /**
         * Review comment
         */
        comment?: string;
    };
    path?: never;
    query?: never;
    url: '/api/reviews';
};

export type PostApiReviewsErrors = {
    /**
     * Invalid data or user already reviewed this place
     */
    400: {
        error: string;
    };
    /**
     * Place not found
     */
    404: {
        error: string;
    };
    /**
     * Internal server error
     */
    500: {
        error: string;
    };
};

export type PostApiReviewsError = PostApiReviewsErrors[keyof PostApiReviewsErrors];

export type PostApiReviewsResponses = {
    /**
     * Review created successfully
     */
    201: {
        id: string;
        rating: number;
        comment: string | null;
        createdAt: string;
        updatedAt: string;
        userId: string;
        placeId: string;
        user?: {
            id: string;
            name: string;
        };
    };
};

export type PostApiReviewsResponse = PostApiReviewsResponses[keyof PostApiReviewsResponses];

export type GetApiReviewsPlaceByPlaceIdData = {
    body?: never;
    path: {
        placeId: string;
    };
    query?: never;
    url: '/api/reviews/place/{placeId}';
};

export type GetApiReviewsPlaceByPlaceIdErrors = {
    /**
     * Place not found
     */
    404: {
        error: string;
    };
    /**
     * Internal server error
     */
    500: {
        error: string;
    };
};

export type GetApiReviewsPlaceByPlaceIdError = GetApiReviewsPlaceByPlaceIdErrors[keyof GetApiReviewsPlaceByPlaceIdErrors];

export type GetApiReviewsPlaceByPlaceIdResponses = {
    /**
     * Reviews retrieved successfully
     */
    200: {
        reviews: Array<{
            id: string;
            rating: number;
            comment: string | null;
            createdAt: string;
            updatedAt: string;
            userId: string;
            placeId: string;
            user?: {
                id: string;
                name: string;
            };
        }>;
        total: number;
        averageRating: number;
    };
};

export type GetApiReviewsPlaceByPlaceIdResponse = GetApiReviewsPlaceByPlaceIdResponses[keyof GetApiReviewsPlaceByPlaceIdResponses];
