// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};

export type PostApiAuthLoginData = {
    body?: {
        /**
         * Email address
         */
        email: string;
        /**
         * Password
         */
        password: string;
    };
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type PostApiAuthLoginErrors = {
    /**
     * Invalid credentials
     */
    401: {
        /**
         * Error message
         */
        error: string;
    };
    /**
     * Internal server error
     */
    500: {
        /**
         * Error message
         */
        error: string;
    };
};

export type PostApiAuthLoginError = PostApiAuthLoginErrors[keyof PostApiAuthLoginErrors];

export type PostApiAuthLoginResponses = {
    /**
     * Login successful
     */
    200: {
        /**
         * JWT authentication token
         */
        token: string;
        user: {
            id: string;
            email: string;
            name: string;
            role: 'USER' | 'ADMIN';
        };
    };
};

export type PostApiAuthLoginResponse = PostApiAuthLoginResponses[keyof PostApiAuthLoginResponses];

export type PostApiAuthRegisterData = {
    body?: {
        /**
         * Email address
         */
        email: string;
        /**
         * Password (minimum 6 characters)
         */
        password: string;
        /**
         * Full name
         */
        name: string;
        /**
         * Phone number
         */
        phoneNumber?: string;
        /**
         * Address
         */
        address?: string;
        /**
         * Number of kids
         */
        numberOfKids?: number;
    };
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type PostApiAuthRegisterErrors = {
    /**
     * Invalid input or email already exists
     */
    400: {
        /**
         * Error message
         */
        error: string;
    };
    /**
     * Internal server error
     */
    500: {
        /**
         * Error message
         */
        error: string;
    };
};

export type PostApiAuthRegisterError = PostApiAuthRegisterErrors[keyof PostApiAuthRegisterErrors];

export type PostApiAuthRegisterResponses = {
    /**
     * Registration successful
     */
    201: {
        /**
         * JWT authentication token
         */
        token: string;
        user: {
            id: string;
            email: string;
            name: string;
            role: 'USER' | 'ADMIN';
        };
    };
};

export type PostApiAuthRegisterResponse = PostApiAuthRegisterResponses[keyof PostApiAuthRegisterResponses];

export type PostApiAuthForgotPasswordData = {
    body?: {
        /**
         * Email address
         */
        email: string;
    };
    path?: never;
    query?: never;
    url: '/api/auth/forgot-password';
};

export type PostApiAuthForgotPasswordErrors = {
    /**
     * User not found
     */
    404: {
        /**
         * Error message
         */
        error: string;
    };
    /**
     * Internal server error
     */
    500: {
        /**
         * Error message
         */
        error: string;
    };
};

export type PostApiAuthForgotPasswordError = PostApiAuthForgotPasswordErrors[keyof PostApiAuthForgotPasswordErrors];

export type PostApiAuthForgotPasswordResponses = {
    /**
     * Password reset email sent
     */
    200: {
        /**
         * Success message
         */
        message: string;
    };
};

export type PostApiAuthForgotPasswordResponse = PostApiAuthForgotPasswordResponses[keyof PostApiAuthForgotPasswordResponses];

export type PostApiAuthResetPasswordData = {
    body?: {
        /**
         * Reset password token
         */
        token: string;
        /**
         * New password (minimum 6 characters)
         */
        newPassword: string;
    };
    path?: never;
    query?: never;
    url: '/api/auth/reset-password';
};

export type PostApiAuthResetPasswordErrors = {
    /**
     * Invalid or expired token
     */
    400: {
        /**
         * Error message
         */
        error: string;
    };
    /**
     * Internal server error
     */
    500: {
        /**
         * Error message
         */
        error: string;
    };
};

export type PostApiAuthResetPasswordError = PostApiAuthResetPasswordErrors[keyof PostApiAuthResetPasswordErrors];

export type PostApiAuthResetPasswordResponses = {
    /**
     * Password reset successful
     */
    200: {
        /**
         * Success message
         */
        message: string;
    };
};

export type PostApiAuthResetPasswordResponse = PostApiAuthResetPasswordResponses[keyof PostApiAuthResetPasswordResponses];

export type GetApiPlacesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Search by name or address
         */
        search?: string;
        /**
         * Filter by place type
         */
        placeType?: 'INDOOR' | 'OUTDOOR';
        /**
         * Minimum age
         */
        minAge?: string;
        /**
         * Maximum age
         */
        maxAge?: string;
        /**
         * Number of results
         */
        limit?: string;
        /**
         * Offset for pagination
         */
        offset?: string;
    };
    url: '/api/places';
};

export type GetApiPlacesErrors = {
    /**
     * Internal server error
     */
    500: {
        error: string;
    };
};

export type GetApiPlacesError = GetApiPlacesErrors[keyof GetApiPlacesErrors];

export type GetApiPlacesResponses = {
    /**
     * List of places
     */
    200: {
        places: Array<{
            id: string;
            name: string;
            description: string | null;
            address: string;
            latitude: number;
            longitude: number;
            placeType: 'INDOOR' | 'OUTDOOR';
            minAge: number;
            maxAge: number;
            area: number | null;
            openingTime: string | null;
            closingTime: string | null;
            phoneNumber: string | null;
            website: string | null;
            imageUrl: string | null;
            averageRating: number;
            totalReviews: number;
            createdAt: string;
            updatedAt: string;
        }>;
        total: number;
    };
};

export type GetApiPlacesResponse = GetApiPlacesResponses[keyof GetApiPlacesResponses];

export type GetApiPlacesByIdData = {
    body?: never;
    path: {
        /**
         * Place ID
         */
        id: string;
    };
    query?: never;
    url: '/api/places/{id}';
};

export type GetApiPlacesByIdErrors = {
    /**
     * Place not found
     */
    404: {
        error: string;
    };
    /**
     * Internal server error
     */
    500: {
        error: string;
    };
};

export type GetApiPlacesByIdError = GetApiPlacesByIdErrors[keyof GetApiPlacesByIdErrors];

export type GetApiPlacesByIdResponses = {
    /**
     * Place details
     */
    200: {
        id: string;
        name: string;
        description: string | null;
        address: string;
        latitude: number;
        longitude: number;
        placeType: 'INDOOR' | 'OUTDOOR';
        minAge: number;
        maxAge: number;
        area: number | null;
        openingTime: string | null;
        closingTime: string | null;
        phoneNumber: string | null;
        website: string | null;
        imageUrl: string | null;
        averageRating: number;
        totalReviews: number;
        createdAt: string;
        updatedAt: string;
    };
};

export type GetApiPlacesByIdResponse = GetApiPlacesByIdResponses[keyof GetApiPlacesByIdResponses];

export type PostApiPlacesImportFromMapData = {
    body?: {
        /**
         * Place ID from Goong Maps
         */
        place_id: string;
        /**
         * Type of place
         */
        placeType: 'INDOOR' | 'OUTDOOR';
        /**
         * Minimum age
         */
        minAge: number;
        /**
         * Maximum age
         */
        maxAge: number;
    };
    path?: never;
    query?: never;
    url: '/api/places/import-from-map';
};

export type PostApiPlacesImportFromMapErrors = {
    /**
     * Invalid data or place already exists
     */
    400: {
        error: string;
    };
    /**
     * Place not found on Goong Maps
     */
    404: {
        error: string;
    };
    /**
     * Internal server error
     */
    500: {
        error: string;
    };
};

export type PostApiPlacesImportFromMapError = PostApiPlacesImportFromMapErrors[keyof PostApiPlacesImportFromMapErrors];

export type PostApiPlacesImportFromMapResponses = {
    /**
     * Place imported successfully
     */
    201: {
        id: string;
        name: string;
        description: string | null;
        address: string;
        latitude: number;
        longitude: number;
        placeType: 'INDOOR' | 'OUTDOOR';
        minAge: number;
        maxAge: number;
        area: number | null;
        openingTime: string | null;
        closingTime: string | null;
        phoneNumber: string | null;
        website: string | null;
        imageUrl: string | null;
        averageRating: number;
        totalReviews: number;
        createdAt: string;
        updatedAt: string;
    };
};

export type PostApiPlacesImportFromMapResponse = PostApiPlacesImportFromMapResponses[keyof PostApiPlacesImportFromMapResponses];

export type PatchApiPlacesByPlaceIdData = {
    body?: {
        /**
         * Additional description
         */
        description?: string;
        /**
         * Area in square meters
         */
        area?: number;
        /**
         * Opening time (HH:mm format)
         */
        openingTime?: string;
        /**
         * Closing time (HH:mm format)
         */
        closingTime?: string;
        /**
         * Additional image URL
         */
        imageUrl?: string;
    };
    path: {
        /**
         * Place ID
         */
        placeId: string;
    };
    query?: never;
    url: '/api/places/{placeId}';
};

export type PatchApiPlacesByPlaceIdErrors = {
    /**
     * Access denied
     */
    403: {
        error: string;
    };
    /**
     * Place not found
     */
    404: {
        error: string;
    };
    /**
     * Internal server error
     */
    500: {
        error: string;
    };
};

export type PatchApiPlacesByPlaceIdError = PatchApiPlacesByPlaceIdErrors[keyof PatchApiPlacesByPlaceIdErrors];

export type PatchApiPlacesByPlaceIdResponses = {
    /**
     * Place updated successfully
     */
    200: {
        id: string;
        name: string;
        description: string | null;
        address: string;
        latitude: number;
        longitude: number;
        placeType: 'INDOOR' | 'OUTDOOR';
        minAge: number;
        maxAge: number;
        area: number | null;
        openingTime: string | null;
        closingTime: string | null;
        phoneNumber: string | null;
        website: string | null;
        imageUrl: string | null;
        averageRating: number;
        totalReviews: number;
        createdAt: string;
        updatedAt: string;
    };
};

export type PatchApiPlacesByPlaceIdResponse = PatchApiPlacesByPlaceIdResponses[keyof PatchApiPlacesByPlaceIdResponses];

export type GetApiMapsPlaceTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/maps/place-types';
};

export type GetApiMapsPlaceTypesResponses = {
    /**
     * List of available place types
     */
    200: {
        categories: Array<{
            name: string;
            types: Array<string>;
            description: string;
        }>;
    };
};

export type GetApiMapsPlaceTypesResponse = GetApiMapsPlaceTypesResponses[keyof GetApiMapsPlaceTypesResponses];

export type GetApiMapsAutocompleteData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Search input text
         */
        input: string;
        location?: string;
        limit?: string;
        radius?: string;
        sessiontoken?: string;
        more_compound?: string;
    };
    url: '/api/maps/autocomplete';
};

export type GetApiMapsAutocompleteErrors = {
    /**
     * Internal server error
     */
    500: {
        error: string;
    };
};

export type GetApiMapsAutocompleteError = GetApiMapsAutocompleteErrors[keyof GetApiMapsAutocompleteErrors];

export type GetApiMapsAutocompleteResponses = {
    /**
     * Autocomplete suggestions
     */
    200: {
        status: string;
        predictions: Array<{
            description: string;
            place_id: string;
            structured_formatting: {
                main_text: string;
                secondary_text?: string;
            };
        }>;
    };
};

export type GetApiMapsAutocompleteResponse = GetApiMapsAutocompleteResponses[keyof GetApiMapsAutocompleteResponses];

export type GetApiMapsPlaceDetailsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Place ID
         */
        place_id: string;
    };
    url: '/api/maps/place-details';
};

export type GetApiMapsPlaceDetailsErrors = {
    /**
     * Place not found
     */
    404: {
        error: string;
    };
    /**
     * Internal server error
     */
    500: {
        error: string;
    };
};

export type GetApiMapsPlaceDetailsError = GetApiMapsPlaceDetailsErrors[keyof GetApiMapsPlaceDetailsErrors];

export type GetApiMapsPlaceDetailsResponses = {
    /**
     * Place details
     */
    200: {
        status: string;
        result: {
            place_id: string;
            name: string;
            formatted_address: string;
            vicinity?: string;
            geometry: {
                location: {
                    lat: number;
                    lng: number;
                };
            };
            types?: Array<string>;
            rating?: number;
            user_ratings_total?: number;
            photos?: Array<{
                photo_reference?: string;
                height?: number;
                width?: number;
                url?: string;
            }>;
            phone_number?: string;
            website?: string;
            opening_hours?: {
                open_now?: boolean;
                weekday_text?: Array<string>;
            };
            editorial_summary?: {
                overview?: string;
            };
        };
        html_attributions?: Array<string>;
    };
};

export type GetApiMapsPlaceDetailsResponse = GetApiMapsPlaceDetailsResponses[keyof GetApiMapsPlaceDetailsResponses];

export type GetApiMapsSearchNearbyWithDetailsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Search keyword
         */
        input: string;
        location?: string;
        latitude?: string;
        longitude?: string;
        radius?: string;
        limit?: string;
        /**
         * Place type filter (e.g., park, restaurant, museum) - will be added to search query
         */
        type?: string;
        profile?: string;
    };
    url: '/api/maps/search-nearby-with-details';
};

export type GetApiMapsSearchNearbyWithDetailsErrors = {
    /**
     * Internal server error
     */
    500: {
        error: string;
    };
};

export type GetApiMapsSearchNearbyWithDetailsError = GetApiMapsSearchNearbyWithDetailsErrors[keyof GetApiMapsSearchNearbyWithDetailsErrors];

export type GetApiMapsSearchNearbyWithDetailsResponses = {
    /**
     * Places found
     */
    200: {
        status: string;
        results: Array<unknown>;
        total: number;
        searched: number;
    };
};

export type GetApiMapsSearchNearbyWithDetailsResponse = GetApiMapsSearchNearbyWithDetailsResponses[keyof GetApiMapsSearchNearbyWithDetailsResponses];

export type GetApiMapsV2PlaceTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/maps-v2/place-types';
};

export type GetApiMapsV2PlaceTypesResponses = {
    /**
     * List of available place types
     */
    200: {
        categories: Array<{
            name: string;
            types: Array<string>;
            description: string;
        }>;
    };
};

export type GetApiMapsV2PlaceTypesResponse = GetApiMapsV2PlaceTypesResponses[keyof GetApiMapsV2PlaceTypesResponses];

export type GetApiMapsV2AutocompleteData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Search input text
         */
        input: string;
        /**
         * Coordinates for location biased search (lat,lng)
         */
        location?: string;
        /**
         * Limit number of results (default: 10)
         */
        limit?: string;
        /**
         * Search radius from location in km (default: 50)
         */
        radius?: string;
        /**
         * UUID token to group multiple requests in one session
         */
        sessiontoken?: string;
        /**
         * Include district, commune, province info (true/false)
         */
        more_compound?: string;
    };
    url: '/api/maps-v2/autocomplete';
};

export type GetApiMapsV2AutocompleteErrors = {
    /**
     * Internal server error
     */
    500: {
        error: string;
    };
};

export type GetApiMapsV2AutocompleteError = GetApiMapsV2AutocompleteErrors[keyof GetApiMapsV2AutocompleteErrors];

export type GetApiMapsV2AutocompleteResponses = {
    /**
     * Autocomplete suggestions
     */
    200: {
        status: string;
        predictions: Array<{
            description: string;
            place_id: string;
            reference?: string;
            matched_substrings?: Array<{
                length?: number;
                offset?: number;
            }>;
            structured_formatting: {
                main_text: string;
                secondary_text?: string;
            };
            terms?: Array<{
                offset?: number;
                value?: string;
            }>;
            has_children?: boolean;
            display_type?: string;
            score?: number;
            plus_code?: {
                compound_code?: string;
                global_code?: string;
            };
        }>;
        executed_time?: number;
        executed_time_all?: number;
    };
};

export type GetApiMapsV2AutocompleteResponse = GetApiMapsV2AutocompleteResponses[keyof GetApiMapsV2AutocompleteResponses];

export type GetApiMapsV2PlaceDetailsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Place ID
         */
        place_id: string;
    };
    url: '/api/maps-v2/place-details';
};

export type GetApiMapsV2PlaceDetailsErrors = {
    /**
     * Place not found
     */
    404: {
        error: string;
    };
    /**
     * Internal server error
     */
    500: {
        error: string;
    };
};

export type GetApiMapsV2PlaceDetailsError = GetApiMapsV2PlaceDetailsErrors[keyof GetApiMapsV2PlaceDetailsErrors];

export type GetApiMapsV2PlaceDetailsResponses = {
    /**
     * Place details
     */
    200: {
        status: string;
        result: {
            place_id: string;
            name: string;
            formatted_address: string;
            vicinity?: string;
            geometry: {
                location: {
                    lat: number;
                    lng: number;
                };
            };
            types?: Array<string>;
            rating?: number;
            user_ratings_total?: number;
            photos?: Array<{
                photo_reference?: string;
                height?: number;
                width?: number;
                url?: string;
            }>;
            phone_number?: string;
            website?: string;
            opening_hours?: {
                open_now?: boolean;
                weekday_text?: Array<string>;
            };
            editorial_summary?: {
                overview?: string;
            };
        };
        html_attributions?: Array<string>;
    };
};

export type GetApiMapsV2PlaceDetailsResponse = GetApiMapsV2PlaceDetailsResponses[keyof GetApiMapsV2PlaceDetailsResponses];

export type GetApiMapsV2SearchNearbyWithDetailsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Search keyword
         */
        input: string;
        location?: string;
        latitude?: string;
        longitude?: string;
        radius?: string;
        limit?: string;
        /**
         * Place type filter (e.g., restaurant, park, hospital)
         */
        type?: string;
        profile?: string;
    };
    url: '/api/maps-v2/search-nearby-with-details';
};

export type GetApiMapsV2SearchNearbyWithDetailsErrors = {
    /**
     * Internal server error
     */
    500: {
        error: string;
    };
};

export type GetApiMapsV2SearchNearbyWithDetailsError = GetApiMapsV2SearchNearbyWithDetailsErrors[keyof GetApiMapsV2SearchNearbyWithDetailsErrors];

export type GetApiMapsV2SearchNearbyWithDetailsResponses = {
    /**
     * Places found
     */
    200: {
        status: string;
        results: Array<unknown>;
        total: number;
        searched: number;
    };
};

export type GetApiMapsV2SearchNearbyWithDetailsResponse = GetApiMapsV2SearchNearbyWithDetailsResponses[keyof GetApiMapsV2SearchNearbyWithDetailsResponses];

export type PostApiReviewsData = {
    body?: {
        /**
         * Place ID from database
         */
        placeId: string;
        /**
         * Rating from 1 to 5
         */
        rating: number;
        /**
         * Review comment
         */
        comment?: string;
    };
    path?: never;
    query?: never;
    url: '/api/reviews';
};

export type PostApiReviewsErrors = {
    /**
     * Invalid data or user already reviewed this place
     */
    400: {
        error: string;
    };
    /**
     * Place not found
     */
    404: {
        error: string;
    };
    /**
     * Internal server error
     */
    500: {
        error: string;
    };
};

export type PostApiReviewsError = PostApiReviewsErrors[keyof PostApiReviewsErrors];

export type PostApiReviewsResponses = {
    /**
     * Review created successfully
     */
    201: {
        id: string;
        rating: number;
        comment: string | null;
        createdAt: string;
        updatedAt: string;
        userId: string;
        placeId: string;
        user?: {
            id: string;
            name: string;
        };
    };
};

export type PostApiReviewsResponse = PostApiReviewsResponses[keyof PostApiReviewsResponses];

export type GetApiReviewsPlaceByPlaceIdData = {
    body?: never;
    path: {
        placeId: string;
    };
    query?: never;
    url: '/api/reviews/place/{placeId}';
};

export type GetApiReviewsPlaceByPlaceIdErrors = {
    /**
     * Place not found
     */
    404: {
        error: string;
    };
    /**
     * Internal server error
     */
    500: {
        error: string;
    };
};

export type GetApiReviewsPlaceByPlaceIdError = GetApiReviewsPlaceByPlaceIdErrors[keyof GetApiReviewsPlaceByPlaceIdErrors];

export type GetApiReviewsPlaceByPlaceIdResponses = {
    /**
     * Reviews retrieved successfully
     */
    200: {
        reviews: Array<{
            id: string;
            rating: number;
            comment: string | null;
            createdAt: string;
            updatedAt: string;
            userId: string;
            placeId: string;
            user?: {
                id: string;
                name: string;
            };
        }>;
        total: number;
        averageRating: number;
    };
};

export type GetApiReviewsPlaceByPlaceIdResponse = GetApiReviewsPlaceByPlaceIdResponses[keyof GetApiReviewsPlaceByPlaceIdResponses];

export type UploadFileData = {
    body?: {
        /**
         * File to upload
         */
        file: Blob | File;
        /**
         * Folder path (optional)
         */
        folder?: string;
    };
    path?: never;
    query?: never;
    url: '/api/minio/upload';
};

export type UploadFileErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
        details?: string;
    };
    /**
     * Internal server error
     */
    500: {
        error: string;
        details?: string;
    };
};

export type UploadFileError = UploadFileErrors[keyof UploadFileErrors];

export type UploadFileResponses = {
    /**
     * File uploaded successfully
     */
    200: {
        success: boolean;
        fileName: string;
        fileUrl: string;
        fileSize: number;
        contentType: string;
        uploadedAt: string;
    };
};

export type UploadFileResponse = UploadFileResponses[keyof UploadFileResponses];

export type GeneratePresignedUploadUrlData = {
    body?: never;
    path?: never;
    query: {
        /**
         * File name with extension
         */
        fileName: string;
        /**
         * Folder path (optional)
         */
        folder?: string;
        /**
         * URL expiration in seconds (default: 3600)
         */
        expires?: string;
    };
    url: '/api/minio/presigned-upload-url';
};

export type GeneratePresignedUploadUrlErrors = {
    /**
     * Bad request
     */
    400: {
        error: string;
        details?: string;
    };
    /**
     * Internal server error
     */
    500: {
        error: string;
        details?: string;
    };
};

export type GeneratePresignedUploadUrlError = GeneratePresignedUploadUrlErrors[keyof GeneratePresignedUploadUrlErrors];

export type GeneratePresignedUploadUrlResponses = {
    /**
     * Presigned URL generated successfully
     */
    200: {
        uploadUrl: string;
        fileName: string;
        expiresIn: number;
        publicUrl: string;
    };
};

export type GeneratePresignedUploadUrlResponse = GeneratePresignedUploadUrlResponses[keyof GeneratePresignedUploadUrlResponses];

export type GetFileInfoData = {
    body?: never;
    path?: never;
    query: {
        /**
         * File name to get info for
         */
        fileName: string;
    };
    url: '/api/minio/file-info';
};

export type GetFileInfoErrors = {
    /**
     * File not found
     */
    404: {
        error: string;
        details?: string;
    };
    /**
     * Internal server error
     */
    500: {
        error: string;
        details?: string;
    };
};

export type GetFileInfoError = GetFileInfoErrors[keyof GetFileInfoErrors];

export type GetFileInfoResponses = {
    /**
     * File information retrieved successfully
     */
    200: {
        fileName: string;
        size: number;
        lastModified: string;
        contentType: string;
        publicUrl: string;
    };
};

export type GetFileInfoResponse = GetFileInfoResponses[keyof GetFileInfoResponses];

export type DeleteFileData = {
    body?: never;
    path?: never;
    query: {
        /**
         * File name to delete
         */
        fileName: string;
    };
    url: '/api/minio/delete';
};

export type DeleteFileErrors = {
    /**
     * File not found
     */
    404: {
        error: string;
        details?: string;
    };
    /**
     * Internal server error
     */
    500: {
        error: string;
        details?: string;
    };
};

export type DeleteFileError = DeleteFileErrors[keyof DeleteFileErrors];

export type DeleteFileResponses = {
    /**
     * File deleted successfully
     */
    200: {
        success: boolean;
        message: string;
        deletedFile: string;
    };
};

export type DeleteFileResponse = DeleteFileResponses[keyof DeleteFileResponses];

export type ListFilesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Folder prefix to filter files
         */
        prefix?: string;
        /**
         * Maximum number of files to return
         */
        limit?: string;
    };
    url: '/api/minio/files';
};

export type ListFilesErrors = {
    /**
     * Internal server error
     */
    500: {
        error: string;
        details?: string;
    };
};

export type ListFilesError = ListFilesErrors[keyof ListFilesErrors];

export type ListFilesResponses = {
    /**
     * Files listed successfully
     */
    200: {
        files: Array<{
            name: string;
            size: number;
            lastModified: string;
            publicUrl: string;
        }>;
        count: number;
    };
};

export type ListFilesResponse = ListFilesResponses[keyof ListFilesResponses];

export type RefreshBucketPolicyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/minio/refresh-policy';
};

export type RefreshBucketPolicyErrors = {
    /**
     * Internal server error
     */
    500: {
        error: string;
        details?: string;
    };
};

export type RefreshBucketPolicyError = RefreshBucketPolicyErrors[keyof RefreshBucketPolicyErrors];

export type RefreshBucketPolicyResponses = {
    /**
     * Policy refreshed successfully
     */
    200: {
        success: boolean;
        message: string;
        policy?: string;
    };
};

export type RefreshBucketPolicyResponse = RefreshBucketPolicyResponses[keyof RefreshBucketPolicyResponses];

export type GetApiMediaData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by place ID
         */
        placeId?: string;
        /**
         * Filter by media type
         */
        mediaType?: 'IMAGE' | 'VIDEO';
        /**
         * Number of results
         */
        limit?: string;
        /**
         * Offset for pagination
         */
        offset?: string;
    };
    url: '/api/media';
};

export type GetApiMediaErrors = {
    /**
     * Internal server error
     */
    500: {
        error: string;
    };
};

export type GetApiMediaError = GetApiMediaErrors[keyof GetApiMediaErrors];

export type GetApiMediaResponses = {
    /**
     * List of media files
     */
    200: {
        media: Array<{
            id: string;
            fileName: string;
            fileUrl: string;
            fileSize: number | null;
            mimeType: string | null;
            mediaType: 'IMAGE' | 'VIDEO';
            title: string | null;
            altText: string | null;
            sortOrder: number;
            placeId: string;
            uploadedBy: string | null;
            createdAt: string;
            updatedAt: string;
            isActive: boolean;
        }>;
        total: number;
    };
};

export type GetApiMediaResponse = GetApiMediaResponses[keyof GetApiMediaResponses];

export type PostApiMediaData = {
    body?: {
        /**
         * ID của địa điểm
         */
        placeId: string;
        /**
         * Public URL của file từ MinIO
         */
        fileUrl: string;
        /**
         * Tên file gốc
         */
        fileName: string;
        /**
         * Kích thước file (bytes)
         */
        fileSize?: number;
        /**
         * MIME type của file
         */
        mimeType?: string;
        /**
         * Loại media
         */
        mediaType: 'IMAGE' | 'VIDEO';
        /**
         * Tiêu đề cho media
         */
        title?: string;
        /**
         * Alt text cho accessibility
         */
        altText?: string;
        /**
         * Thứ tự hiển thị
         */
        sortOrder?: number;
    };
    path?: never;
    query?: never;
    url: '/api/media';
};

export type PostApiMediaErrors = {
    /**
     * Invalid data
     */
    400: {
        error: string;
    };
    /**
     * Place not found
     */
    404: {
        error: string;
    };
    /**
     * Internal server error
     */
    500: {
        error: string;
    };
};

export type PostApiMediaError = PostApiMediaErrors[keyof PostApiMediaErrors];

export type PostApiMediaResponses = {
    /**
     * Media created successfully
     */
    201: {
        id: string;
        fileName: string;
        fileUrl: string;
        fileSize: number | null;
        mimeType: string | null;
        mediaType: 'IMAGE' | 'VIDEO';
        title: string | null;
        altText: string | null;
        sortOrder: number;
        placeId: string;
        uploadedBy: string | null;
        createdAt: string;
        updatedAt: string;
        isActive: boolean;
    };
};

export type PostApiMediaResponse = PostApiMediaResponses[keyof PostApiMediaResponses];

export type DeleteApiMediaByIdData = {
    body?: never;
    path: {
        /**
         * Media ID
         */
        id: string;
    };
    query?: never;
    url: '/api/media/{id}';
};

export type DeleteApiMediaByIdErrors = {
    /**
     * Access denied
     */
    403: {
        error: string;
    };
    /**
     * Media not found
     */
    404: {
        error: string;
    };
    /**
     * Internal server error
     */
    500: {
        error: string;
    };
};

export type DeleteApiMediaByIdError = DeleteApiMediaByIdErrors[keyof DeleteApiMediaByIdErrors];

export type DeleteApiMediaByIdResponses = {
    /**
     * Media deleted successfully
     */
    200: {
        success: boolean;
        message: string;
    };
};

export type DeleteApiMediaByIdResponse = DeleteApiMediaByIdResponses[keyof DeleteApiMediaByIdResponses];

export type PatchApiMediaByIdData = {
    body?: {
        /**
         * Tiêu đề cho media
         */
        title?: string;
        /**
         * Alt text cho accessibility
         */
        altText?: string;
        /**
         * Thứ tự hiển thị
         */
        sortOrder?: number;
        /**
         * Trạng thái active
         */
        isActive?: boolean;
    };
    path: {
        /**
         * Media ID
         */
        id: string;
    };
    query?: never;
    url: '/api/media/{id}';
};

export type PatchApiMediaByIdErrors = {
    /**
     * Access denied
     */
    403: {
        error: string;
    };
    /**
     * Media not found
     */
    404: {
        error: string;
    };
    /**
     * Internal server error
     */
    500: {
        error: string;
    };
};

export type PatchApiMediaByIdError = PatchApiMediaByIdErrors[keyof PatchApiMediaByIdErrors];

export type PatchApiMediaByIdResponses = {
    /**
     * Media updated successfully
     */
    200: {
        id: string;
        fileName: string;
        fileUrl: string;
        fileSize: number | null;
        mimeType: string | null;
        mediaType: 'IMAGE' | 'VIDEO';
        title: string | null;
        altText: string | null;
        sortOrder: number;
        placeId: string;
        uploadedBy: string | null;
        createdAt: string;
        updatedAt: string;
        isActive: boolean;
    };
};

export type PatchApiMediaByIdResponse = PatchApiMediaByIdResponses[keyof PatchApiMediaByIdResponses];
