// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { getApiMapsAutocomplete, getApiMapsNearby, getApiMapsPlaceDetails, getApiMapsPlaceTypes, getApiMapsSearchNearbyWithDetails, getApiPlaces, getApiPlacesById, getApiReviewsPlaceByPlaceId, type Options, postApiAuthLogin, postApiAuthRegister, postApiPlacesImportFromMap, postApiReviews } from '../sdk.gen';
import type { GetApiMapsAutocompleteData, GetApiMapsAutocompleteError, GetApiMapsAutocompleteResponse, GetApiMapsNearbyData, GetApiMapsNearbyError, GetApiMapsNearbyResponse, GetApiMapsPlaceDetailsData, GetApiMapsPlaceDetailsError, GetApiMapsPlaceDetailsResponse, GetApiMapsPlaceTypesData, GetApiMapsPlaceTypesResponse, GetApiMapsSearchNearbyWithDetailsData, GetApiMapsSearchNearbyWithDetailsError, GetApiMapsSearchNearbyWithDetailsResponse, GetApiPlacesByIdData, GetApiPlacesByIdError, GetApiPlacesByIdResponse, GetApiPlacesData, GetApiPlacesError, GetApiPlacesResponse, GetApiReviewsPlaceByPlaceIdData, GetApiReviewsPlaceByPlaceIdError, GetApiReviewsPlaceByPlaceIdResponse, PostApiAuthLoginData, PostApiAuthLoginError, PostApiAuthLoginResponse, PostApiAuthRegisterData, PostApiAuthRegisterError, PostApiAuthRegisterResponse, PostApiPlacesImportFromMapData, PostApiPlacesImportFromMapError, PostApiPlacesImportFromMapResponse, PostApiReviewsData, PostApiReviewsError, PostApiReviewsResponse } from '../types.gen';

/**
 * Login
 *
 * Authenticate user and return JWT token
 */
export const postApiAuthLoginMutation = (options?: Partial<Options<PostApiAuthLoginData>>): UseMutationOptions<PostApiAuthLoginResponse, PostApiAuthLoginError, Options<PostApiAuthLoginData>> => {
    const mutationOptions: UseMutationOptions<PostApiAuthLoginResponse, PostApiAuthLoginError, Options<PostApiAuthLoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiAuthLogin({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Register
 *
 * Create new user account
 */
export const postApiAuthRegisterMutation = (options?: Partial<Options<PostApiAuthRegisterData>>): UseMutationOptions<PostApiAuthRegisterResponse, PostApiAuthRegisterError, Options<PostApiAuthRegisterData>> => {
    const mutationOptions: UseMutationOptions<PostApiAuthRegisterResponse, PostApiAuthRegisterError, Options<PostApiAuthRegisterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiAuthRegister({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const getApiPlacesQueryKey = (options?: Options<GetApiPlacesData>) => createQueryKey("getApiPlaces", options);

/**
 * Get all places
 *
 * Get list of places with optional filters
 */
export const getApiPlacesOptions = (options?: Options<GetApiPlacesData>) => queryOptions<GetApiPlacesResponse, GetApiPlacesError, GetApiPlacesResponse, ReturnType<typeof getApiPlacesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiPlaces({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiPlacesQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = {
        ...queryKey[0]
    };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const getApiPlacesInfiniteQueryKey = (options?: Options<GetApiPlacesData>): QueryKey<Options<GetApiPlacesData>> => createQueryKey("getApiPlaces", options, true);

/**
 * Get all places
 *
 * Get list of places with optional filters
 */
export const getApiPlacesInfiniteOptions = (options?: Options<GetApiPlacesData>) => {
    return infiniteQueryOptions<GetApiPlacesResponse, GetApiPlacesError, InfiniteData<GetApiPlacesResponse>, QueryKey<Options<GetApiPlacesData>>, string | Pick<QueryKey<Options<GetApiPlacesData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<GetApiPlacesData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    offset: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await getApiPlaces({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getApiPlacesInfiniteQueryKey(options)
    });
};

export const getApiPlacesByIdQueryKey = (options: Options<GetApiPlacesByIdData>) => createQueryKey("getApiPlacesById", options);

/**
 * Get place by ID
 */
export const getApiPlacesByIdOptions = (options: Options<GetApiPlacesByIdData>) => queryOptions<GetApiPlacesByIdResponse, GetApiPlacesByIdError, GetApiPlacesByIdResponse, ReturnType<typeof getApiPlacesByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiPlacesById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiPlacesByIdQueryKey(options)
});

/**
 * Import place from Goong Maps
 *
 * Fetch place details from Goong Maps and save to database
 */
export const postApiPlacesImportFromMapMutation = (options?: Partial<Options<PostApiPlacesImportFromMapData>>): UseMutationOptions<PostApiPlacesImportFromMapResponse, PostApiPlacesImportFromMapError, Options<PostApiPlacesImportFromMapData>> => {
    const mutationOptions: UseMutationOptions<PostApiPlacesImportFromMapResponse, PostApiPlacesImportFromMapError, Options<PostApiPlacesImportFromMapData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiPlacesImportFromMap({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiMapsNearbyQueryKey = (options: Options<GetApiMapsNearbyData>) => createQueryKey("getApiMapsNearby", options);

/**
 * [DEPRECATED] Search nearby places
 *
 * DEPRECATED: This endpoint uses old Track-Asia API. Please use /maps/search-nearby-with-details or /maps/autocomplete with Goong API instead.
 */
export const getApiMapsNearbyOptions = (options: Options<GetApiMapsNearbyData>) => queryOptions<GetApiMapsNearbyResponse, GetApiMapsNearbyError, GetApiMapsNearbyResponse, ReturnType<typeof getApiMapsNearbyQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiMapsNearby({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiMapsNearbyQueryKey(options)
});

export const getApiMapsPlaceDetailsQueryKey = (options: Options<GetApiMapsPlaceDetailsData>) => createQueryKey("getApiMapsPlaceDetails", options);

/**
 * Get place details
 *
 * Get detailed information about a specific place using Goong Maps API
 */
export const getApiMapsPlaceDetailsOptions = (options: Options<GetApiMapsPlaceDetailsData>) => queryOptions<GetApiMapsPlaceDetailsResponse, GetApiMapsPlaceDetailsError, GetApiMapsPlaceDetailsResponse, ReturnType<typeof getApiMapsPlaceDetailsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiMapsPlaceDetails({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiMapsPlaceDetailsQueryKey(options)
});

export const getApiMapsPlaceTypesQueryKey = (options?: Options<GetApiMapsPlaceTypesData>) => createQueryKey("getApiMapsPlaceTypes", options);

/**
 * Get available place types
 *
 * Get list of place types that can be used for nearby search
 */
export const getApiMapsPlaceTypesOptions = (options?: Options<GetApiMapsPlaceTypesData>) => queryOptions<GetApiMapsPlaceTypesResponse, DefaultError, GetApiMapsPlaceTypesResponse, ReturnType<typeof getApiMapsPlaceTypesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiMapsPlaceTypes({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiMapsPlaceTypesQueryKey(options)
});

export const getApiMapsAutocompleteQueryKey = (options: Options<GetApiMapsAutocompleteData>) => createQueryKey("getApiMapsAutocomplete", options);

/**
 * Autocomplete place search
 *
 * Get autocomplete suggestions for place search
 */
export const getApiMapsAutocompleteOptions = (options: Options<GetApiMapsAutocompleteData>) => queryOptions<GetApiMapsAutocompleteResponse, GetApiMapsAutocompleteError, GetApiMapsAutocompleteResponse, ReturnType<typeof getApiMapsAutocompleteQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiMapsAutocomplete({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiMapsAutocompleteQueryKey(options)
});

export const getApiMapsSearchNearbyWithDetailsQueryKey = (options: Options<GetApiMapsSearchNearbyWithDetailsData>) => createQueryKey("getApiMapsSearchNearbyWithDetails", options);

/**
 * Search nearby places with full details
 *
 * Combines autocomplete and place-details APIs, filters by distance and type
 */
export const getApiMapsSearchNearbyWithDetailsOptions = (options: Options<GetApiMapsSearchNearbyWithDetailsData>) => queryOptions<GetApiMapsSearchNearbyWithDetailsResponse, GetApiMapsSearchNearbyWithDetailsError, GetApiMapsSearchNearbyWithDetailsResponse, ReturnType<typeof getApiMapsSearchNearbyWithDetailsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiMapsSearchNearbyWithDetails({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiMapsSearchNearbyWithDetailsQueryKey(options)
});

/**
 * Create a review
 *
 * Create a new review for a place
 */
export const postApiReviewsMutation = (options?: Partial<Options<PostApiReviewsData>>): UseMutationOptions<PostApiReviewsResponse, PostApiReviewsError, Options<PostApiReviewsData>> => {
    const mutationOptions: UseMutationOptions<PostApiReviewsResponse, PostApiReviewsError, Options<PostApiReviewsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiReviews({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiReviewsPlaceByPlaceIdQueryKey = (options: Options<GetApiReviewsPlaceByPlaceIdData>) => createQueryKey("getApiReviewsPlaceByPlaceId", options);

/**
 * Get place reviews
 *
 * Get all reviews for a specific place
 */
export const getApiReviewsPlaceByPlaceIdOptions = (options: Options<GetApiReviewsPlaceByPlaceIdData>) => queryOptions<GetApiReviewsPlaceByPlaceIdResponse, GetApiReviewsPlaceByPlaceIdError, GetApiReviewsPlaceByPlaceIdResponse, ReturnType<typeof getApiReviewsPlaceByPlaceIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiReviewsPlaceByPlaceId({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiReviewsPlaceByPlaceIdQueryKey(options)
});
